module.exports = {
    secret: "eyJ0eXAiOiJKV1QiLCJhbGciOiJFUzI1NiIsImtpZCI6ImExZGE0YmMyOGFmY2IwYjYwMTU5OGUzN2UxZjVmOTM5In0.e30.sajgDN5qWaeQbuxvcOljOzJ5_i9PfFGv_BQedQh91AzGOemErDDNQblUz4RjNnPGStlslUaXvRvqnpeaK6ohCA",
};
